name: Check Holiday Updates
description: Monitor holiday file freshness and create GitHub issues for outdated files
author: Arkadii Yakovets

inputs:
  dry_run:
    description: Dry run mode (no issues created)
    required: false
    default: 'false'
  github_token:
    description: GitHub token for API access
    required: true
  paths:
    description: List of paths/globs to check for holiday files
    required: true
  repository:
    description: Repository where issues will be created (owner/repo)
    required: false
    default: 'vacanza/holidays'
  threshold_days:
    description: Age threshold for files in days
    required: false
    default: '180'

outputs:
  issues_created_count:
    description: Total number of GitHub issues created
  outdated_files_count:
    description: Total number of outdated files found

runs:
  using: docker
  image: Dockerfile
  args:
    - --dry-run
    - ${{ inputs.dry_run }}
    - --paths
    - ${{ inputs.paths }}
    - --github-token
    - ${{ inputs.github_token }}
    - --repository
    - ${{ inputs.repository }}
    - --threshold-days
    - ${{ inputs.threshold_days }}
